---
version: '3.8'

services:
  nso:
    image: cisco-nso:5.7
    container_name: nso
    ports:
      - "8080:8080"
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
    restart: unless-stopped
    