Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
  
    config.vm.define "nso" do |nso|
      nso.vm.hostname = "nso-lab"
      nso.vm.network "private_network", ip: "192.168.56.10"
    end
  
    config.vm.define "n8n" do |n8n|
      n8n.vm.hostname = "n8n-lab"
      n8n.vm.network "private_network", ip: "192.168.56.11"
    end
  end