---
name: Basic Test

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  placeholder-tests:
    name: placeholder-tests
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
