name: Lint Check

"on":
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Satisfy expected "Lint Check / lint"
        run: echo "ok"
